id: IAAC9953E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:38:44+00:00'
last_modified: '2022-06-08T02:38:00.622981+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ4826
  title: 'དབྱངས་ཅན་བརྡ་སྤྲོད་ཀྱི་འགྲེལ་པ་མཆོག་ཏུ་གསལ་བ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1EC1:
      image_group_id: I1KG9017
      title: ''
      total_pages: 884
      order: 1
      base_file: 1EC1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
